- id: '1695220711402'
  alias: boiler_on_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_on
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.livingroom_trv_temp_switch_on
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.bedroom_trv_temp_switch_on
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.spare_room_1_trv_temp_switch_on
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.at_least_one_trv_active
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.livingroom_trv_temp_switch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.bedroom_trv_temp_switch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.spare_room_1_trv_temp_switch_on
      state: 'on'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.boiler_thermostat_thermostat
      temperature: 24
      hvac_mode: heat
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.study_trv_temp_switch_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.livingroom_trv_temp_switch_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bedroom_trv_temp_switch_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.spare_room_1_trv_temp_switch_on
        state: 'off'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1695220839312'
  alias: boiler_off_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
    - binary_sensor.livingroom_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
    - binary_sensor.bedroom_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
    - binary_sensor.spare_room_1_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.livingroom_trv_temp_switch_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.bedroom_trv_temp_switch_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.spare_room_1_trv_temp_switch_on
      state: 'off'
    alias: Test that all TRVs temps are below set temp
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- alias: livingroom_set_temp_schedule_on
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_livingroom
  condition: '{{ trigger.to_state.state in [''on''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_2
    data:
      temperature: 16.5
      hvac_mode: heat
  id: 80644456db0f44119aaf718df9530b48
- alias: livingroom_set_temp_schedule_off
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_livingroom
  condition: '{{ trigger.to_state.state in [''off''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_2
    data:
      temperature: 7
      hvac_mode: heat
  id: ad4c3b05b0d14994a9878a090d3d39f3
- alias: bedroom_set_temp_schedule_on
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_bedroom
  condition: '{{ trigger.to_state.state in [''on''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_3
    data:
      temperature: 17
      hvac_mode: heat
  id: f37ee745a4994966a33d7ba8c1a093c2
- alias: bedroom_set_temp_schedule_off
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_bedroom
  condition: '{{ trigger.to_state.state in [''off''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_3
    data:
      temperature: 7
      hvac_mode: heat
  id: 9f369381ea0c4bc092e865ddcda64e83
- id: '1697623210880'
  alias: iris_home_heat
  description: Iris only home
  trigger:
  - platform: state
    entity_id: input_button.iris_is_home_heating
  action:
  - service: automation.trigger
    entity_id:
    - automation.boiler_on_binary_sensor
    - automation.boiler_off_binary_sensor
    - automation.livingroom_set_temp_schedule_off_5
    - automation.livingroom_set_temp_schedule_on_3
    - automation.bedroom_set_temp_test
  mode: single
- id: '1698078005986'
  alias: bedroom_set_temp_scheduled
  description: Set bedroom thermostat to on and off temps
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_bedroom
  condition: []
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_3
    data:
      temperature: '{{ iif(trigger.to_state.state == ''on'', 17, 7) }}'
      hvac_mode: heat
  mode: single
- id: '1698153653547'
  description: Set bedroom thermostat to on and off temps
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_bedroom
  condition: []
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_3
    data:
      temperature: '{{ iif(trigger.to_state.state == ''on'', 17, 7) }}'
      hvac_mode: heat
  mode: single
- id: '1698153675738'
  alias: livingroom_set_temp_scheduled
  description: Set livingroom thermostat to on and off temps
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_livingroom
  condition:
  - condition: device
    device_id: f365704d295f41afee6f6d5b7a8d49b0
    domain: climate
    entity_id: f2abf0a18da1ea1ff0c9973d02a7cec5
    type: is_hvac_mode
    hvac_mode: heat
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_2
    data:
      temperature: '{{ iif(trigger.to_state.state == ''on'', 17.5, 7) }}'
      hvac_mode: heat
  mode: single
- id: '1698154033800'
  alias: spareroom_1_set_temp_scheduled
  description: Set spare thermostat to on and off temps
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_spareroom_1
  condition: []
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.aqara_trv_spare_room_1_thermostat
    data:
      temperature: '{{ iif(trigger.to_state.state == ''on'', 17, 7) }}'
      hvac_mode: heat
  mode: single
- id: '1698400662120'
  alias: pause_livingroom_heat_schedule
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.pause_run_livingroom
  condition: []
  action:
  - device_id: f365704d295f41afee6f6d5b7a8d49b0
    domain: climate
    entity_id: f2abf0a18da1ea1ff0c9973d02a7cec5
    type: set_hvac_mode
    hvac_mode: 'off'
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: binary_sensor.at_least_one_trv_heating
      state: 'off'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  - delay: '{{(states(''input_number.heating_pause_hrs_livingroom'')|int) * 3600}}'
  - device_id: f365704d295f41afee6f6d5b7a8d49b0
    domain: climate
    entity_id: f2abf0a18da1ea1ff0c9973d02a7cec5
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1698578557279'
  alias: pause_bedroom_heat_schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_number.heating_pause_hrs_bedroom
  condition: []
  action:
  - device_id: 1046a437bd3e2efb2c02dbfdc956c08a
    domain: climate
    entity_id: e142c2b8e0d54c1c61bf352aecb84ac9
    type: set_hvac_mode
    hvac_mode: 'off'
  - delay: '{{(states(''input_number.heating_pause_hrs_bedroomroom'')|int) * 3600}}'
  - device_id: 1046a437bd3e2efb2c02dbfdc956c08a
    domain: climate
    entity_id: e142c2b8e0d54c1c61bf352aecb84ac9
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1698579295792'
  alias: pause_study_heat_schedule
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.pause_run_study
  condition: []
  action:
  - device_id: 0ba8f70e7545714f072c05bbba69e792
    domain: climate
    entity_id: 2d6fa43f6144bb6b0544cbcc778509dc
    type: set_hvac_mode
    hvac_mode: 'off'
  - delay: '{{(states(''input_number.heating_pause_hrs_study'')|int) * 3600}}'
  - device_id: 0ba8f70e7545714f072c05bbba69e792
    domain: climate
    entity_id: 2d6fa43f6144bb6b0544cbcc778509dc
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1698579646741'
  alias: pause_spareroom_1_heat_schedule
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.pause_run_spareroom_1
  condition: []
  action:
  - device_id: b7d32ff1c653c6248b94bb95b4a5a9a5
    domain: climate
    entity_id: 38611b45592603cc049d12faab3a0a13
    type: set_hvac_mode
    hvac_mode: 'off'
  - delay: '{{(states(''input_number.heating_pause_hrs_spareroom_1'')|int) * 3600}}'
  - device_id: b7d32ff1c653c6248b94bb95b4a5a9a5
    domain: climate
    entity_id: 38611b45592603cc049d12faab3a0a13
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1699274525583'
  alias: cancel_pause_run_livingroom
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.cancel_pause_run_livingroom
  condition: []
  action:
  - device_id: f365704d295f41afee6f6d5b7a8d49b0
    domain: climate
    entity_id: f2abf0a18da1ea1ff0c9973d02a7cec5
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
