- id: '1685360232964'
  alias: Boiler on
  description: Turn on boiler when study below min temp
  trigger:
  - platform: device
    device_id: 0ba8f70e7545714f072c05bbba69e792
    domain: climate
    entity_id: climate.lumi_lumi_airrtc_agl001_thermostat
    type: current_temperature_changed
    below: 5
    for:
      hours: 0
      minutes: 2
      seconds: 0
    enabled: false
  - platform: state
    entity_id:
    - binary_sensor.study_trv_on
    to: 'on'
    id: study_trv_sensor
  condition: []
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: climate.boiler_thermostat_thermostat
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1694523978428'
  alias: boiler control fixed temp
  description: ''
  trigger:
  - platform: device
    device_id: 0ba8f70e7545714f072c05bbba69e792
    domain: climate
    entity_id: 2d6fa43f6144bb6b0544cbcc778509dc
    type: current_temperature_changed
    below: 7
    id: study_trv_on
  condition:
  - condition: device
    device_id: 0ba8f70e7545714f072c05bbba69e792
    domain: climate
    entity_id: 2d6fa43f6144bb6b0544cbcc778509dc
    type: is_hvac_mode
    hvac_mode: heat
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1694526611715'
  alias: Boiler control template
  description: ''
  trigger:
  - platform: template
    value_template: "{% if int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"current_temperature\")) < int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"temperature\")) %}\n  True\n{% else %}\n  False\n{% endif %}"
    id: study_trv_on
  - platform: template
    value_template: "{% if int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"current_temperature\")) > int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"temperature\")) %}\n  True\n{% else %}\n  False\n{% endif %}"
    id: study_trv_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - study_trv_on
        enabled: false
      sequence:
      - device_id: cd11a01a85f99087427fcea9e2514b37
        domain: climate
        entity_id: 30a8b83ee300274727a37de10e9d30b7
        type: set_hvac_mode
        hvac_mode: heat
    - conditions:
      - condition: trigger
        id:
        - study_trv_off
      sequence:
      - device_id: cd11a01a85f99087427fcea9e2514b37
        domain: climate
        entity_id: 30a8b83ee300274727a37de10e9d30b7
        type: set_hvac_mode
        hvac_mode: 'off'
  mode: restart
- id: '1695220711402'
  alias: boiler_on_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_off
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.at_least_one_trv_active
    state: 'on'
  - condition: state
    entity_id: binary_sensor.study_trv_temp_switch_on
    state: 'on'
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: heat
  - if:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_on
      state: 'off'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1695220839312'
  alias: boiler_off_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_off
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.study_trv_temp_switch_off
    state: 'on'
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: 'off'
  - if:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_off
      state: 'on'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
