- id: '1695220711402'
  alias: boiler_on_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_on
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.livingroom_trv_temp_switch_on
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.bedroom_trv_temp_switch_on
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.spare_room_1_trv_temp_switch_on
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.at_least_one_trv_active
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.livingroom_trv_temp_switch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.bedroom_trv_temp_switch_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.spare_room_1_trv_temp_switch_on
      state: 'on'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.boiler_thermostat_thermostat
      temperature: 24
      hvac_mode: heat
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.study_trv_temp_switch_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.livingroom_trv_temp_switch_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bedroom_trv_temp_switch_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.spare_room_1_trv_temp_switch_on
        state: 'off'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1695220839312'
  alias: boiler_off_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.livingroom_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.bedroom_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.spare_room_1_trv_temp_switch_on
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.livingroom_trv_temp_switch_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.bedroom_trv_temp_switch_on
      state: 'off'
    - condition: state
      entity_id: binary_sensor.spare_room_1_trv_temp_switch_on
      state: 'off'
    alias: Test that all TRVs temps are below set temp
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- alias: livingroom_set_temp_schedule_on
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_livingroom
  condition: '{{ trigger.to_state.state in [''on''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_2
    data:
      temperature: 16.5
      hvac_mode: heat
  id: 80644456db0f44119aaf718df9530b48
- alias: livingroom_set_temp_schedule_off
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_livingroom
  condition: '{{ trigger.to_state.state in [''off''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_2
    data:
      temperature: 7
      hvac_mode: heat
  id: ad4c3b05b0d14994a9878a090d3d39f3
- alias: bedroom_set_temp_schedule_on
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_bedroom
  condition: '{{ trigger.to_state.state in [''on''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_3
    data:
      temperature: 17
      hvac_mode: heat
  id: f37ee745a4994966a33d7ba8c1a093c2
- alias: bedroom_set_temp_schedule_off
  trigger:
  - platform: state
    entity_id: schedule.thermostat_schedule_bedroom
  condition: '{{ trigger.to_state.state in [''off''] }}'
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.lumi_lumi_airrtc_agl001_thermostat_3
    data:
      temperature: 7
      hvac_mode: heat
  id: 9f369381ea0c4bc092e865ddcda64e83
- id: '1697623210880'
  alias: iris_home_heat
  description: Iris only home
  trigger:
  - platform: state
    entity_id: input_button.iris_is_home_heating
  action:
  - service: automation.trigger
    entity_id:
    - automation.boiler_on_binary_sensor
    - automation.boiler_off_binary_sensor
    - automation.bedroom_set_temp_schedule_on
    - automation.bedroom_set_temp_schedule_off
    - automation.livingroom_set_temp_schedule_off_5
    - automation.livingroom_set_temp_schedule_on_3
  mode: single
