- id: '1694526611715'
  alias: Boiler control template
  description: ''
  trigger:
  - platform: template
    value_template: "{% if int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"current_temperature\")) < int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"temperature\")) %}\n  True\n{% else %}\n  False\n{% endif %}"
    id: study_trv_on
  - platform: template
    value_template: "{% if int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"current_temperature\")) > int(state_attr(\"climate.lumi_lumi_airrtc_agl001_thermostat\",
      \"temperature\")) %}\n  True\n{% else %}\n  False\n{% endif %}"
    id: study_trv_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - study_trv_on
        enabled: false
      sequence:
      - device_id: cd11a01a85f99087427fcea9e2514b37
        domain: climate
        entity_id: 30a8b83ee300274727a37de10e9d30b7
        type: set_hvac_mode
        hvac_mode: heat
    - conditions:
      - condition: trigger
        id:
        - study_trv_off
      sequence:
      - device_id: cd11a01a85f99087427fcea9e2514b37
        domain: climate
        entity_id: 30a8b83ee300274727a37de10e9d30b7
        type: set_hvac_mode
        hvac_mode: 'off'
  mode: restart
- id: '1695220711402'
  alias: boiler_on_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_off
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.at_least_one_trv_active
    state: 'on'
  - condition: state
    entity_id: binary_sensor.study_trv_temp_switch_on
    state: 'on'
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: heat
  - if:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_on
      state: 'off'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1695220839312'
  alias: boiler_off_binary_sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_trv_temp_switch_off
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.study_trv_temp_switch_off
    state: 'on'
  action:
  - device_id: cd11a01a85f99087427fcea9e2514b37
    domain: climate
    entity_id: 30a8b83ee300274727a37de10e9d30b7
    type: set_hvac_mode
    hvac_mode: 'off'
  - if:
    - condition: state
      entity_id: binary_sensor.study_trv_temp_switch_off
      state: 'on'
    then:
    - device_id: cd11a01a85f99087427fcea9e2514b37
      domain: climate
      entity_id: 30a8b83ee300274727a37de10e9d30b7
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
