
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
light:
  - platform: trv
    name: "Thermostatic radiator valves"


       
template:
    - binary_sensor:
      - name: "at_least_one_trv_active"
      #- description: "Binary indicator for at least one trv being in the on state for switching on the boiler"
        state: >
          {% if is_state("climate.lumi_lumi_airrtc_agl001_thermostat", "heat") %}
            True
          {% else %}
            False
          {% endif %}
      - name: "study_trv_temp_switch_on"
        state: >
          {{ int(state_attr("climate.lumi_lumi_airrtc_agl001_thermostat", "current_temperature")) < int(state_attr("climate.lumi_lumi_airrtc_agl001_thermostat", "temperature")) }}
      - name: "study_trv_temp_switch_off"
        state: >
          {{ int(state_attr("climate.lumi_lumi_airrtc_agl001_thermostat", "current_temperature")) > int(state_attr("climate.lumi_lumi_airrtc_agl001_thermostat", "temperature")) }}
          
          
